# Generated by Django 5.2.1 on 2025-05-09 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('bus_type', models.CharField(max_length=20)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('reaching_time', models.TimeField()),
                ('start_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('via', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('bus_type', models.CharField(max_length=20)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('reaching_time', models.TimeField()),
                ('start_point', models.CharField(max_length=100)),
                ('destination_point', models.CharField(max_length=100)),
                ('via', models.TextField()),
            ],
        ),
    ]
