# Generated by Django 5.2.1 on 2025-05-09 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='train',
            old_name='bus_type',
            new_name='train_type',
        ),
    ]
