# Generated by Django 5.2.1 on 2025-05-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0003_train_days_of_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='via_times',
            field=models.TextField(default='N/A', help_text='Comma-separated times matching each via stop (e.g., 09:30,10:00,10:30)'),
        ),
        migrations.AddField(
            model_name='train',
            name='via_times',
            field=models.TextField(default='N/A', help_text='Comma-separated times matching each via stop (e.g., 09:30,10:00,10:30)'),
        ),
    ]
